### ISSUE TITLE
Error on airnode windows 10pro64bit

### ISSUE THREAD

**Issue by pronetla** [coinscrow/minerstat-airnode#1]
Hi i cant test airnode for asic miner, when i put Farm ID  on airnode windows a popup start saying "check your internet conecction" this is a fresh windows installer

![error](https://user-images.githubusercontent.com/34408473/33801514-df59356a-dd33-11e7-97dd-f2097745fdda.jpg)

**Comment by coinscrow** [comment]
I just noticed your Issue, I'm checking now and publish a fix for that as soon as possible.

**Comment by coinscrow** [comment]
https://github.com/coinscrow/minerstat-airnode/releases/latest

**Comment by coinscrow** [comment]
Resolved, thank you for reporting.
